name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    name: Release and Publish (Bun)
    runs-on: ubuntu-latest

    steps:
      # Generate Token for the GitHub App
      - name: Generate GitHub App Token
        id: generate-token
        # Uses App ID and Private Key secrets to generate a short-lived installation token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0
          persist-credentials: true

      - name: âš¡ Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: ğŸ“¥ Install dependencies with Bun
        run: bun install

      - name: ğŸ— Build project
        run: bun run build

      - name: ğŸš€ Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 21
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
          dry_run: false
          install_plugins_command: "bun install"
        env:
          github_token: ${{ steps.generate-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: ğŸ“¡ Publish to JSR
        run: npx jsr publish
